version: '4'
services:
  feature-flag-manager-frontend:
    build: ./feature-flag-manager-frontend
    ports:
      - "80:80"
    depends_on:
      - feature-flag-manager-service
  feature-flag-manager-service:
    build: ./feature-flag-manager-service
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata