server:
  port: 80

spring:
  application:
    name: feature flag manager Service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl:
        auto: <create | create-drop | update | validate | none>
      dialect: org.hibernate.dialect.PostgreSQLDialect
